language: java
jdk: openjdk7

env:
  global:
  - TERM=dumb
  - secure: "DU5sznUhdYMK2h974ihHnuKsQVORwfSRHQHd3IBM+IwUBh2dzb3eOCJYWowekNp0LxBND2YSCti8EjD/9Zo/9W/Km9aV5zDRFnctzLQX4cYcssqtt0bUrXkgzIW7A8ou6vRcVdjp4Zp/jfGAJxC7TWCIoxell0Id49yLNMcBYns="
  - secure: "XWkv3pk/hEJB7BDudPH3x9zk541Bl1yb5PynDRkMSUrKeeU2E0hFX1qATvy+gwadIFoqqlDDemtKjURBJq5nyTuWVJZ0StkH3PMdSjjMymzzBmf1RsB+EmpemG/wldXLys5S/jtlsZ/cQuqC/R4hgyTLr86YM/KdsfPBu0lsyM0="
  - secure: "mNC9zY3ztFoVIIyhOU2i6FUGkV81YSiKxYuderHN9ScuACYngE2F+ggp5ZphEoRqQqkn/YaqymMwrOUtbGK0JT8C29E3fJIiW+zryV/OJdu/ed5/yfkwTHQGYp9kdlP6MlERSstG3z04CT44GcuW0BqA6ySsgJvnlBYMzz211yw="

branches:
  only:
  - master
  - develop

notifications:
  email: false
  irc: chat.freenode.net#syncany

before_install:
- sudo apt-get update
- sudo apt-get install -y -q lftp
- lftp -v

script:
- core/gradlew pluginJar

after_success:
- core/gradle/lftp/lftpuploadplugin.sh

